# 1. Load Pandas and Iris dataset

In [13]:
# Load Pandas and Iris dataset

import pandas as pd
import numpy as np

df=pd.read_csv("./IrisDataset.csv")
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

  species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa

In [17]:
df.sample(10) #dataframe sample

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
54,6.5,2.8,4.6,1.5,versicolor
71,6.1,2.8,4.0,1.3,versicolor
117,7.7,3.8,6.7,2.2,virginica
30,4.8,3.1,1.6,0.2,setosa
58,6.6,2.9,4.6,1.3,versicolor
81,5.5,2.4,3.7,1.0,versicolor
10,5.4,3.7,1.5,0.2,setosa
64,5.6,2.9,3.6,1.3,versicolor
51,6.4,3.2,4.5,1.5,versicolor
28,5.2,3.4,1.4,0.2,setosa

## 1.1. Data Simulation

In [12]:
np.random.seed(42)
for col in ['petal_length', 'petal_width']:
    indices = np.random.choice(df.index, 5, replace=False)
    df.loc[indices, col] = np.nan

print("Dataset loaded and modified with NaN values.")

Dataset loaded and modified with NaN values.

## 1.2. Dataframe Information

In [ ]:
print("All dataframe info:")
df.info()

All dataframe info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   species            150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

## 1.3. Statistics

In [16]:
print("Statistics")
df.describe()

Statistics

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

## 1.4. Search the column I want

In [33]:
df[['sepal length (cm)', 'sepal width (cm)']]

     sepal length (cm)  sepal width (cm)
0                  5.1               3.5
1                  4.9               3.0
2                  4.7               3.2
3                  4.6               3.1
4                  5.0               3.6
..                 ...               ...
145                6.7               3.0
146                6.3               2.5
147                6.5               3.0
148                6.2               3.4
149                5.9               3.0

[150 rows x 2 columns]

# 2. Cardinality and Exploratory Data Analysis

## 2.1. Print total of species (unique and nunique)

In [18]:
print("Total of species:", df['species'].nunique())

Total of species: 3

In [19]:
print("Total of species:", df['species'].unique())

Total of species: ['setosa' 'versicolor' 'virginica']

## 2.2. Print count of each species

In [20]:
print ("Count of each species:")
print(df['species'].value_counts())

Count of each species:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

# 3. Clear all data

## 3.1. Check for null values

In [23]:
print("Null values in each column: \n", df.isnull().sum())

Null values in each column:
 sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64

## 3.2. Fill null values with mean / data

In [34]:
df['petal_length (cm)'] = df['petal_length (cm)'].fillna(df['petal_length (cm)'].mean())
df['petal_width (cm)'] = df['petal_width (cm)'].fillna(df['petal_width (cm)'].mean())

print("Null values after filling with mean: \n", df.isnull().sum().sum())

KeyError: 'petal_length (cm)'

# 4. Transformation (Future Engineering)

## 4.1. Converting the column species to numbers

In [36]:
species_mapping = {'setosa': 0, 'versicolor': 1, 'virginica': 2}

df["target_species"] = df["species"].map(species_mapping)

print("Dataframe with new column 'target_species':")
print(df[['species', 'target_species']].sample(5))

Dataframe with new column 'target_species':
        species  target_species
120   virginica               2
110   virginica               2
123   virginica               2
94   versicolor               1
6        setosa               0

In [ ]:
df # Show the entire dataframe and th rounded values came from the mean

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species,target_species
0,5.1,3.5,1.4,0.2,setosa,0
1,4.9,3.0,1.4,0.2,setosa,0
2,4.7,3.2,1.3,0.2,setosa,0
3,4.6,3.1,1.5,0.2,setosa,0
4,5.0,3.6,1.4,0.2,setosa,0
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,2
146,6.3,2.5,5.0,1.9,virginica,2
147,6.5,3.0,5.2,2.0,virginica,2
148,6.2,3.4,5.4,2.3,virginica,2
149,5.9,3.0,5.1,1.8,virginica,2

# 5. Analysis Correlation

In [40]:
df_numeric = df.drop('species', axis=1)
print("Correlation matrix:")
print(df_numeric.corr())

Correlation matrix:
                   sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754
sepal width (cm)           -0.117570          1.000000          -0.428440
petal length (cm)           0.871754         -0.428440           1.000000
petal width (cm)            0.817941         -0.366126           0.962865
target_species              0.782561         -0.426658           0.949035

                   petal width (cm)  target_species
sepal length (cm)          0.817941        0.782561
sepal width (cm)          -0.366126       -0.426658
petal length (cm)          0.962865        0.949035
petal width (cm)           1.000000        0.956547
target_species             0.956547        1.000000